export const CONST_ACTIONS_BASKET ={
    SHOW_BASKET: "SHOW_BASKET",
    PUT_IN_BASKET: "PUT_IN_BASKET",
    ADD_SERVICE: "ADD_SERVICE",
    DISSMISS_SERVICE: "DISSMISS_SERVICE",
    DELETE_SERVICE: "DELETE_SERVICE",
};