export const Const = {
  min: 1,
  max: 10,
  SLIDER_ITEM: 4,
  ACTIONS: {
    FETCH_DATA_LENGTH: "FETCH_DATA_LENGTH",
    FETCH_DATA_ARRAY: "FETCH_DATA_ARRAY",
    FETCH_DATA_ARRAY_RENDER: "FETCH_DATA_ARRAY_RENDER",
    SERVICES_IS_LOADING: "SERVICES_IS_LOADING",
    ERROR: "ERROR",
    SHOW_BASKET: "SHOW_BASKET",
    PUT_IN_BASKET: "PUT_IN_BASKET",
    ADD_SERVICE: "ADD_SERVICE",
    DISSMISS_SERVICE: "DISSMISS_SERVICE",
    DELETE_SERVICE: "DELETE_SERVICE"
  }
};
